// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// whichMinDist
int whichMinDist(NumericMatrix x, NumericVector y);
RcppExport SEXP _DEEButil_whichMinDist(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(whichMinDist(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distToVec
NumericVector distToVec(NumericMatrix x, NumericVector y);
RcppExport SEXP _DEEButil_distToVec(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(distToVec(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distSqrToVec
NumericVector distSqrToVec(NumericMatrix target, NumericVector query);
RcppExport SEXP _DEEButil_distSqrToVec(SEXP targetSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(distSqrToVec(target, query));
    return rcpp_result_gen;
END_RCPP
}
// expKernelMatrix
NumericMatrix expKernelMatrix(NumericMatrix state, double bandwidth, double regulation);
RcppExport SEXP _DEEButil_expKernelMatrix(SEXP stateSEXP, SEXP bandwidthSEXP, SEXP regulationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type state(stateSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type regulation(regulationSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelMatrix(state, bandwidth, regulation));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVector
NumericVector expKernelVector(NumericVector xout, NumericMatrix x, double bandwidth);
RcppExport SEXP _DEEButil_expKernelVector(SEXP xoutSEXP, SEXP xSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVector(xout, x, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVectors
NumericMatrix expKernelVectors(NumericMatrix xout, NumericMatrix x, double bandwidth);
RcppExport SEXP _DEEButil_expKernelVectors(SEXP xoutSEXP, SEXP xSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVectors(xout, x, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelDerivVector
NumericMatrix expKernelDerivVector(NumericVector xout, NumericMatrix x, double bandwidth);
RcppExport SEXP _DEEButil_expKernelDerivVector(SEXP xoutSEXP, SEXP xSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelDerivVector(xout, x, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVectorFromDistSqr
NumericVector expKernelVectorFromDistSqr(NumericVector distSqr, double bandwidth);
RcppExport SEXP _DEEButil_expKernelVectorFromDistSqr(SEXP distSqrSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type distSqr(distSqrSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVectorFromDistSqr(distSqr, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelMatrix1D
NumericMatrix expKernelMatrix1D(NumericVector x, double bandwidth, double regulation);
RcppExport SEXP _DEEButil_expKernelMatrix1D(SEXP xSEXP, SEXP bandwidthSEXP, SEXP regulationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type regulation(regulationSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelMatrix1D(x, bandwidth, regulation));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVectors1D
NumericMatrix expKernelVectors1D(NumericVector x, NumericVector xout, double bandwidth);
RcppExport SEXP _DEEButil_expKernelVectors1D(SEXP xSEXP, SEXP xoutSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVectors1D(x, xout, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelDerivVectors1D
NumericMatrix expKernelDerivVectors1D(NumericVector x, NumericVector xout, double bandwidth);
RcppExport SEXP _DEEButil_expKernelDerivVectors1D(SEXP xSEXP, SEXP xoutSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelDerivVectors1D(x, xout, bandwidth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DEEButil_whichMinDist", (DL_FUNC) &_DEEButil_whichMinDist, 2},
    {"_DEEButil_distToVec", (DL_FUNC) &_DEEButil_distToVec, 2},
    {"_DEEButil_distSqrToVec", (DL_FUNC) &_DEEButil_distSqrToVec, 2},
    {"_DEEButil_expKernelMatrix", (DL_FUNC) &_DEEButil_expKernelMatrix, 3},
    {"_DEEButil_expKernelVector", (DL_FUNC) &_DEEButil_expKernelVector, 3},
    {"_DEEButil_expKernelVectors", (DL_FUNC) &_DEEButil_expKernelVectors, 3},
    {"_DEEButil_expKernelDerivVector", (DL_FUNC) &_DEEButil_expKernelDerivVector, 3},
    {"_DEEButil_expKernelVectorFromDistSqr", (DL_FUNC) &_DEEButil_expKernelVectorFromDistSqr, 2},
    {"_DEEButil_expKernelMatrix1D", (DL_FUNC) &_DEEButil_expKernelMatrix1D, 3},
    {"_DEEButil_expKernelVectors1D", (DL_FUNC) &_DEEButil_expKernelVectors1D, 3},
    {"_DEEButil_expKernelDerivVectors1D", (DL_FUNC) &_DEEButil_expKernelDerivVectors1D, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DEEButil(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
