# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
whichMinDist <- function(x, y) {
    .Call(`_DEEButil_whichMinDist`, x, y)
}

#' @export
distToVec <- function(x, y) {
    .Call(`_DEEButil_distToVec`, x, y)
}

#' @export
distSqrToVec <- function(target, query) {
    .Call(`_DEEButil_distSqrToVec`, target, query)
}

#' @export
expKernelMatrix <- function(state, bandwidth, regulation) {
    .Call(`_DEEButil_expKernelMatrix`, state, bandwidth, regulation)
}

#' @export
expKernelVector <- function(xout, x, bandwidth) {
    .Call(`_DEEButil_expKernelVector`, xout, x, bandwidth)
}

#' @export
expKernelVectors <- function(xout, x, bandwidth) {
    .Call(`_DEEButil_expKernelVectors`, xout, x, bandwidth)
}

#' @export
expKernelDerivVector <- function(xout, x, bandwidth) {
    .Call(`_DEEButil_expKernelDerivVector`, xout, x, bandwidth)
}

#' @export
expKernelVectorFromDistSqr <- function(distSqr, bandwidth) {
    .Call(`_DEEButil_expKernelVectorFromDistSqr`, distSqr, bandwidth)
}

#' @export
expKernelMatrix1D <- function(x, bandwidth, regulation) {
    .Call(`_DEEButil_expKernelMatrix1D`, x, bandwidth, regulation)
}

#' @export
expKernelVectors1D <- function(x, xout, bandwidth) {
    .Call(`_DEEButil_expKernelVectors1D`, x, xout, bandwidth)
}

#' @export
expKernelDerivVectors1D <- function(x, xout, bandwidth) {
    .Call(`_DEEButil_expKernelDerivVectors1D`, x, xout, bandwidth)
}

