# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the index of the closest row.
#'
#' @param target A n x p matrix.
#' @param query A vector of length p.
#' @returns The smallest index of a row of target that has the smallest
#'   Euclidean distance to query.
#' @export
whichMinDist <- function(target, query) {
    .Call(`_DEEButil_whichMinDist`, target, query)
}

#' @export
distToVec <- function(x, y) {
    .Call(`_DEEButil_distToVec`, x, y)
}

#' @export
distSqrToVec <- function(target, query) {
    .Call(`_DEEButil_distSqrToVec`, target, query)
}

#' @export
distSqrToSeg <- function(u, v0, v1) {
    .Call(`_DEEButil_distSqrToSeg`, u, v0, v1)
}

#' @export
distSqrToPwLin <- function(path, query) {
    .Call(`_DEEButil_distSqrToPwLin`, path, query)
}

#' @export
whichMinDistToPwLin <- function(path, id, query) {
    .Call(`_DEEButil_whichMinDistToPwLin`, path, id, query)
}

#' @export
expKernelMatrix <- function(state, bandwidth, regulation) {
    .Call(`_DEEButil_expKernelMatrix`, state, bandwidth, regulation)
}

#' @export
expKernelVector <- function(xout, x, bandwidth) {
    .Call(`_DEEButil_expKernelVector`, xout, x, bandwidth)
}

#' @export
expKernelVectors <- function(xout, x, bandwidth) {
    .Call(`_DEEButil_expKernelVectors`, xout, x, bandwidth)
}

#' @export
expKernelDerivVector <- function(xout, x, bandwidth) {
    .Call(`_DEEButil_expKernelDerivVector`, xout, x, bandwidth)
}

#' @export
expKernelVectorFromDistSqr <- function(distSqr, bandwidth) {
    .Call(`_DEEButil_expKernelVectorFromDistSqr`, distSqr, bandwidth)
}

#' @export
expKernelMatrix1D <- function(x, bandwidth, regulation) {
    .Call(`_DEEButil_expKernelMatrix1D`, x, bandwidth, regulation)
}

#' @export
expKernelVectors1D <- function(x, xout, bandwidth) {
    .Call(`_DEEButil_expKernelVectors1D`, x, xout, bandwidth)
}

#' @export
expKernelDerivVectors1D <- function(x, xout, bandwidth) {
    .Call(`_DEEButil_expKernelDerivVectors1D`, x, xout, bandwidth)
}

#' @export
minDistTimeState <- function(query, target, time, scale) {
    .Call(`_DEEButil_minDistTimeState`, query, target, time, scale)
}

#' @export
minDist <- function(query, target) {
    .Call(`_DEEButil_minDist`, query, target)
}

#' Evaluate Monomials.
#'
#' @param x A n x d matrix. The n input vectors, each of dimension d.
#' @param degrees A p x d matrix. The degrees of the p output monomial for each of the d dimensions.
#' @returns A n x p matrix. The values of the p monomials for each of the n inputs vectors.
#' @export
evaluateMonomials <- function(x, degrees) {
    .Call(`_DEEButil_evaluateMonomials`, x, degrees)
}

#' Get exponents of a degree deg polynomial in dim dimensions.
#'
#' @param dimension A positive integer. The dimension of the space.
#' @param degree A nonegative integer. The degreee of the polynomial.
#' @returns A p x d integer matrix. The exponents for the p = (dim + deg choose deg) terms of the polynomial.
#' @export
getMonomialExponents <- function(dimension, degree) {
    .Call(`_DEEButil_getMonomialExponents`, dimension, degree)
}

